FROM node:22-slim AS builder

WORKDIR /app

COPY frontend/package*.json ./

RUN npm ci --registry=https://registry.npmmirror.com

COPY frontend/ ./

ENV VITE_BACKEND_SERVER=/
ENV VITE_FILE_BASE_URL=/

RUN npm run build

FROM nginx:stable-alpine

COPY --from=builder /app/dist /usr/share/nginx/html

COPY nginx-frontend.conf /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
